version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: My_Contexts  # has an env var called MY_ENV_VAR

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var references
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our context"
          command: |
            echo "this is my output text" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - ~/output.txt
