version: 2.1

workflows:
  test-env-vars:
    jobs:
      - my_job:
          context: My_Contexts  # has an env var called MY_ENV_VAR
commands:
  print_pipeline_id:
    description: "print the pipeline id to console"
    parameters:
      to:
        type: string
        default: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>
    
jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var references
    steps:
      - checkout
      - print_pipeline_id
      - run: 
          name: "return 1"
          command: | 
            return 1
      - run:
          name: "on fail do this"
          command: |
            echo "YEP THAT FAILED"
            when: on-fail
            


